// ui-cron/projects/ui/src/lib/tabs/hour/hour.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';

import { Segment, CoreService } from '@sbzen/uicron-core';

import { UiCronService } from './../../ui.service';
import { UiTabSingleSegmentComponent } from './../tab-single-segment.component';

@Component({
  selector: 'ui-cron-hour',
  templateUrl: './hour.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class UiHourComponent extends UiTabSingleSegmentComponent {
  hourCodes = this.coreService.getList(Segment.hours, true);
  hours = this.coreService.getList(Segment.hours);

  constructor(
    private coreService: CoreService,
    uiCronService: UiCronService
  ) {
    super(Segment.hours, uiCronService);
  }
}

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.EVERY)"
      [value]="mode.EVERY"
      [checked]="view.selected === mode.EVERY"
      [disabled]="isDisabled()"
      (change)="setEvery()">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.EVERY)">
      Every hour
    </label>
  </div>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.INCREMENT)"
      [value]="mode.INCREMENT"
      [checked]="view.selected === mode.INCREMENT"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.INCREMENT)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.INCREMENT)">
      Every
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(mode.INCREMENT)"
    (change)="setInValue(mode.INCREMENT, 1, $event.target.value)">

    <option
      *ngFor="let item of hourCodes"
      [value]="item.value"
      [selected]="getModelValues(mode.INCREMENT)[1] === item.value">
      {{item.value}}
    </option>
  </select>

  <label [attr.for]="genId(mode.INCREMENT)">
      hour(s) starting at hour
  </label>

  <select
    class="form-control form-control-sm ml-1"
    [disabled]="isDisabled(mode.INCREMENT)"
    (change)="setInValue(mode.INCREMENT, 0, $event.target.value)">

    <option
      *ngFor="let item of hours"
      [value]="item.value"
      [selected]="getModelValues(mode.INCREMENT)[0] === item.value">
      {{item.label}}
    </option>
  </select>
</div>

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.AND)"
      [value]="mode.AND"
      [checked]="view.selected === mode.AND"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.AND)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.AND)">
      Specific hour (choose one or many)
    </label>
  </div>

  <div class="row pl-3 pt-1">
    <div
      *ngFor="let item of hours"
      class="col-1">

      <div class="form-check">
        <input
          class="form-check-input"
          type="checkbox"
          [attr.id]="genId(mode.AND, item.value)"
          [value]="item.value"
          [disabled]="isDisabled(mode.AND)"
          [checked]="inSpecificsList(item.value, mode.AND)"
          (change)="toggleSpecifics(item.value, mode.AND)">

        <label
          class="form-check-label"
          [attr.for]="genId(mode.AND, item.value)">
          {{item.label}}
        </label>
      </div>
    </div>
  </div>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.RANGE)"
      [value]="mode.RANGE"
      [checked]="view.selected === mode.RANGE"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.RANGE)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.RANGE)">
      Every hour between hour
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(mode.RANGE)"
    (change)="setInValue(mode.RANGE, 0, $event.target.value)">

    <option
      *ngFor="let item of hours"
      [value]="item.value"
      [selected]="getModelValues(mode.RANGE)[0] === item.value">
      {{item.label}}
    </option>
  </select>

  <label [attr.for]="genId(mode.RANGE)">and hour</label>

  <select
    class="form-control form-control-sm ml-1"
    [disabled]="isDisabled(mode.RANGE)"
    (change)="setInValue(mode.RANGE, 1, $event.target.value)">

    <option
      *ngFor="let item of hours"
      [value]="item.value"
      [selected]="getModelValues(mode.RANGE)[1] === item.value">
      {{item.label}}
    </option>
  </select>
</div>

// libs/re-cron/src/lib/tabs/hour/hour.tsx
import React from 'react';
import { Segment, CoreService, Mode } from '@sbzen/cron-core';

import { QuartzCronDI } from './../../cron-di';
import { TabBaseProps } from './../tab-base.component';
import { TabSingleSegmentComponent, TabSingleSegmentState } from './../tab-single-segment.component';

type Option = {
	value: string;
	label: string;
}

type ReCronHourState = {
	hourCodes: Option[];
	hours: Option[];
} & TabSingleSegmentState;

export class ReCronHour extends TabSingleSegmentComponent<ReCronHourState> {
	constructor(props: TabBaseProps) {
		super(Segment.hours, props);

		this.state = {
			hourCodes: new CoreService().getList(Segment.hours, true),
			hours: new CoreService().getList(Segment.hours),
			view: QuartzCronDI.get(this.props.session).getView(Segment.hours)
		};
	}

	render() {
		return (
			<div>
				<div className={this.genClassName(['form-group'], ['c-every'])}>
					<div className={this.genClassName(['form-check'], ['c-every-check'])}>
						<input
							className={this.genClassName(['form-check-input'], ['c-every-option'])}
							type="radio"
							id={this.genId(Mode.EVERY)}
							value={Mode.EVERY}
							checked={this.state.view.selected === Mode.EVERY}
							disabled={this.isDisabled()}
							onChange={() => {this.setEvery()}} />

						<label
							className={this.genClassName(['form-check-label'], ['c-every-option-label'])}
							htmlFor={this.genId(Mode.EVERY)}>
							Every hour
						</label>
					</div>
				</div>
				
				<div className={this.genClassName(['form-group', 'form-inline'], ['c-increment'])}>
					<div className={this.genClassName(['form-check'], ['c-increment-check'])}>
					
						<input
							className={this.genClassName(['form-check-input'], ['c-increment-option'])}
							type="radio"
							id={this.genId(Mode.INCREMENT)}
							value={Mode.INCREMENT}
							checked={this.state.view.selected === Mode.INCREMENT}
							disabled={this.isDisabled()}
							onChange={() => this.setSelected(Mode.INCREMENT)} />

						<label
							className={this.genClassName(['form-check-label'], ['c-increment-option-label'])}
							htmlFor={this.genId(Mode.INCREMENT)}>
							Every
						</label>
					</div>

					<select
						className={this.genClassName(['form-control', 'form-control-sm', 'mx-1'], ['c-increment-every'])}
						disabled={this.isDisabled(Mode.INCREMENT)}
						value={this.getModelValues(Mode.INCREMENT)[1]}
						onChange={(e) => this.setInValue(Mode.INCREMENT, 1, e.target.value)}>

						{this.state.hourCodes.map(item => {
							return (
								<option
									key={item.value}
									value={item.value}>
									{item.value}
								</option>
							);
						})}
					</select>

					<label
						className="c-increment-option-label2"
						htmlFor={this.genId(Mode.INCREMENT)}>
						hour(s) starting at hour
					</label>

					<select
						className={this.genClassName(['form-control', 'form-control-sm', 'ml-1'], ['c-increment-from'])}
						disabled={this.isDisabled(Mode.INCREMENT)}
						value={this.getModelValues(Mode.INCREMENT)[0]}
						onChange={(e) => this.setInValue(Mode.INCREMENT, 0, e.target.value)}>

						{this.state.hours.map(item => {
							return (
								<option
									key={item.value}
									value={item.value}>
									{item.label}
								</option>
							);
						})}
					</select>
				</div>

				<div className={this.genClassName(['form-group'], ['c-and'])}>
					<div className={this.genClassName(['form-check'], ['c-and-check'])}>
						<input
							className={this.genClassName(['form-check-input'], ['c-and-option'])}
							type="radio"
							id={this.genId(Mode.AND)}
							value={Mode.AND}
							checked={this.state.view.selected === Mode.AND}
							disabled={this.isDisabled()}
							onChange={() => this.setSelected(Mode.AND)} />

						<label
							className={this.genClassName(['form-check-label'], ['c-and-option-label'])}
							htmlFor={this.genId(Mode.AND)}>
							Specific hour (choose one or many)
						</label>
					</div>

					<div className={this.genClassName(['row', 'pl-3', 'pt-1'], ['c-and-list'])}>
						{this.state.hours.map(item => {
							return (
								<div
									className={this.genClassName(['col-1'], ['c-and-item'])}
									item-value={item.value}
									key={this.genId(Mode.AND, item.value)}>
		
									<div className={this.genClassName(['form-check'], ['c-and-item-check'])}>
										<input
											className={this.genClassName(['form-check-input'], ['c-and-item-field'])}
											type="checkbox"
											id={this.genId(Mode.AND, item.value)}
											value={item.value}
											disabled={this.isDisabled(Mode.AND)}
											checked={this.inSpecificsList(item.value, Mode.AND)}
											onChange={() => this.toggleSpecifics(item.value, Mode.AND)} />
		
										<label
											className={this.genClassName(['form-check-label'], ['c-and-item-label'])}
											htmlFor={this.genId(Mode.AND, item.value)}>
											{item.label}
										</label>
									</div>
								</div>
							);
						})}
					</div>
				</div>

				<div className={this.genClassName(['form-group', 'form-inline'], ['c-range'])}>
					<div className={this.genClassName(['form-check'], ['c-range-check'])}>
					
						<input
							className={this.genClassName(['form-check-input'], ['c-range-option'])}
							type="radio"
							id={this.genId(Mode.RANGE)}
							value={Mode.RANGE}
							checked={this.state.view.selected === Mode.RANGE}
							disabled={this.isDisabled()}
							onChange={() => this.setSelected(Mode.RANGE)}/>

						<label
							className={this.genClassName(['form-check-label'], ['c-range-option-label'])}
							htmlFor={this.genId(Mode.RANGE)}>
							Every hour between hour
						</label>
					</div>

					<select
						className={this.genClassName(['form-control', 'form-control-sm', 'mx-1'], ['c-range-from'])}
						disabled={this.isDisabled(Mode.RANGE)}
						value={this.getModelValues(Mode.RANGE)[0]}
						onChange={(e) => this.setInValue(Mode.RANGE, 0, e.target.value)}>

						{this.state.hours.map(item => {
							return (
								<option
									key={item.value}
									value={item.value}>
									{item.label}
								</option>
							);
						})}
					</select>

					<label
						className="c-range-option-label2"
						htmlFor={this.genId(Mode.RANGE)}>
						and hour
					</label>

					<select
						className={this.genClassName(['form-control', 'form-control-sm', 'ml-1'], ['c-range-to'])}
						disabled={this.isDisabled(Mode.RANGE)}
						value={this.getModelValues(Mode.RANGE)[1]}
						onChange={(e) => this.setInValue(Mode.RANGE, 1, e.target.value)}>

						{this.state.hours.map(item => {
							return (
								<option
									key={item.value}
									value={item.value}>
									{item.label}
								</option>
							);
						})}
					</select>
				</div>
			</div>
		);
	}
}
