// libs/ng-cron/src/lib/shared/and/and.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';
import { Mode } from '@sbzen/cron-core';

@Component({
	selector: 'cron-and',
	templateUrl: './and.html',
	changeDetection: ChangeDetectionStrategy.OnPush
})
export class CronAndComponent {
	mode = Mode.AND;
	@Output() selected = new EventEmitter<void>();
	@Input() cssClassPrefix = '';
	@Input() checked = false;
	@Input() disabled = false;
	@Input() disabledControls = false;
	@Input() gridSize = 'col-1';
	@Input() label = '';
	@Input() segmentId = '';
	@Input() options: {
		label: string|number,
		value: string
	}[] = [];
	@Input() isValueSelected: (value: string) => boolean = () => false;
	@Input() selectValue: (value: string) => boolean = () => false;

	constructor(private readonly cd: ChangeDetectorRef) {}

	changeValue(e: Event, value: string) {
		const status = this.selectValue(value);
		if (!status) {
			e.preventDefault();
		}
	}

	detectChanges() {
		this.cd.detectChanges();
	}
}

// libs/re-cron/src/lib/shared/and.tsx
import React from 'react';
import { Mode } from '@sbzen/cron-core';

import { genClassName } from './../helpers';

type Props = {
	cssClassPrefix?: string;
	checked?: boolean;
	disabled?: boolean;
	disabledControls?: boolean;
	onSelect: () => void;
	onValueChange: (value: string) => void;
	isValueSelected: (value: string) => boolean;
	options: {
		label: string|number,
		value: string
	}[],
	label: string;
	gridSize?: string;
	segmentId: string;
}

export const SimpleAnd = ({
	cssClassPrefix = '',
	checked = false,
	disabled = false,
	disabledControls = false,
	label,
	options,
	onSelect,
	onValueChange,
	isValueSelected,
	gridSize = 'col-1',
	segmentId
}: Props) => (
	<div className={genClassName(cssClassPrefix, ['form-group'], ['c-and'])}>
		<div className={genClassName(cssClassPrefix, ['form-check'], ['c-and-check'])}>
			<input
				className={genClassName(cssClassPrefix, ['form-check-input'], ['c-and-option'])}
				type="radio"
				id={segmentId}
				value={Mode.AND}
				checked={checked}
				disabled={disabled}
				onChange={onSelect} />

			<label
				className={genClassName(cssClassPrefix, ['form-check-label'], ['c-and-option-label'])}
				htmlFor={segmentId}>
				{label}
			</label>
		</div>

		<div className={genClassName(cssClassPrefix, ['row', 'pl-3', 'pt-1'], ['c-and-list'])}>
			{options.map(item => {
				return (
					<div
						className={genClassName(cssClassPrefix, [gridSize], ['c-and-item'])}
						item-value={item.value}
						key={item.value}>

						<div className={genClassName(cssClassPrefix, ['form-check'], ['c-and-item-check'])}>
							<input
								className={genClassName(cssClassPrefix, ['form-check-input'], ['c-and-item-field'])}
								type="checkbox"
								id={`${segmentId}_${item.value}`}
								value={item.value}
								disabled={disabledControls}
								checked={isValueSelected(item.value)}
								onChange={() => onValueChange(item.value)} />

							<label
								className={genClassName(cssClassPrefix, ['form-check-label'], ['c-and-item-label'])}
								htmlFor={`${segmentId}_${item.value}`}>
								{item.label}
							</label>
						</div>
					</div>
				);
			})}
		</div>
	</div>
);
