// libs/ng-cron/src/lib/shared/every/every.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { Mode } from '@sbzen/cron-core';

@Component({
	selector: 'cron-every',
	templateUrl: './every.html',
	changeDetection: ChangeDetectionStrategy.OnPush
})
export class CronEveryComponent {
	@Output() selected = new EventEmitter<void>();
	@Input() cssClassPrefix = '';
	@Input() checked = false;
	@Input() disabled = false;
	@Input() label = '';
	@Input() segmentId = '';
	mode = Mode.EVERY;
}

// libs/re-cron/src/lib/shared/every.tsx
import React from 'react';
import { Mode } from '@sbzen/cron-core';

import { genClassName } from './../helpers';

type Props = {
	cssClassPrefix?: string;
	checked?: boolean;
	disabled?: boolean;
	onSelect: () => void;
	label: string;
	segmentId: string;
}

export const SimpleEvery = ({
	cssClassPrefix = '',
	checked = false,
	disabled = false,
	label,
	onSelect,
	segmentId
}: Props) => (
	<div className={genClassName(cssClassPrefix, ['form-group'], ['c-every'])}>
		<div className={genClassName(cssClassPrefix, ['form-check'], ['c-every-check'])}>
			<input
				className={genClassName(cssClassPrefix, ['form-check-input'], ['c-every-option'])}
				type="radio"
				id={segmentId}
				value={Mode.EVERY}
				checked={checked}
				disabled={disabled}
				onChange={onSelect} />

			<label
				className={genClassName(cssClassPrefix, ['form-check-label'], ['c-every-option-label'])}
				htmlFor={segmentId}>
				{label}
			</label>
		</div>
	</div>
);
