// libs/cron-bootstrap/src/lib/tabs/day/day.component.ts
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';

import { Mode, Segment, ViewDataItem, CoreService } from '@sbzen/core';

import { CronBootstrapService } from './../../cron.service';
import { TabBaseComponent } from './../tab-base.component';

type TabSegments = Segment.dayOfMonth|Segment.dayOfWeek;

@Component({
  selector: 'cron-day',
  templateUrl: './day.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DayComponent extends TabBaseComponent {
  @Input() dayOfMonth: ViewDataItem;
  @Input() dayOfWeek: ViewDataItem;

  mode = Mode;
  segment = Segment;
  daysOfWeekEvery = this.coreService.getList(Segment.dayOfWeek, true);
  daysOfWeek = this.coreService.getList(Segment.dayOfWeek);
  daysOfWeekCodes = this.coreService.getDaysOfWeekCodes();

  daysOfMonthEvery = this.coreService.getList(Segment.dayOfMonth, true);
  daysOfMonth = this.coreService.getList(Segment.dayOfMonth);
  limitedDaysOfMonth = this.daysOfMonthEvery.slice(0, 5);

  resets = {
    daysOfMonth: () => {
      this.dayOfMonth.selected = Mode.NONE;
      this.dayOfMonth.values.NONE.values = ['?'];
    },
    daysOfWeek: () => {
      this.dayOfWeek.selected = Mode.NONE;
      this.dayOfWeek.values.NONE.values = ['?'];
    }
  };

  constructor(
    private coreService: CoreService,
    private cronBootstrap: CronBootstrapService
  ) {
    super();
  }

  setEvery() {
    this.dayOfMonth.values.NONE.values = ['?'];
    this.dayOfWeek.values.EVERY.values = ['*'];
    this.dayOfWeek.selected = Mode.EVERY;
    this.applyChanges();
  }

  setSelected(mode: Mode, segment: TabSegments, reset?: TabSegments, value?: string) {
    this[segment].selected = mode;
    if (reset === Segment.dayOfMonth) {
      this.resets.daysOfMonth();
    }
    if (reset === Segment.dayOfWeek) {
      this.resets.daysOfWeek();
    }
    if (value) {
      this.setInValue(mode, segment, 0, value);
    }
    this.applyChanges();
  }

  isDisabled(segment?: TabSegments, mode?: Mode) {
    let disabled = this.disableFields;
    if (segment && mode) {
      disabled = disabled || this[segment].selected !== mode;
    }
    return disabled;
  }

  setInValue(mode: Mode, segment: TabSegments, index: 0|1, value: string) {
    const source = this.getModelValues(mode, segment);
    source[index] = value;
    this.applyChanges();
  }

  getModelValues(mode: Mode, segment: TabSegments) {
    return this[segment].values[mode].values;
  }

  inSpecificsList(value: string, mode: Mode, segment: TabSegments) {
    return this.cronBootstrap.hasValue(value, segment, mode);
  }

  toggleSpecifics(value: string, mode: Mode, segment: TabSegments) {
    const values = this.cronBootstrap.getValues(segment, mode);
    if (!values.includes(value)) {
      values.push(value);
      this.applyChanges();
      return;
    }

    const i = values.indexOf(value);
    values.splice(i, 1);
    this.applyChanges();
  }
}

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.EVERY, segment.dayOfWeek)"
      [value]="mode.EVERY"
      [checked]="dayOfWeek.selected === mode.EVERY"
      [disabled]="isDisabled()"
      (change)="setEvery()">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.EVERY, segment.dayOfWeek)">

      Every day
    </label>
  </div>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.INCREMENT, segment.dayOfWeek)"
      [value]="mode.INCREMENT"
      [checked]="dayOfWeek.selected === mode.INCREMENT"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.INCREMENT, segment.dayOfWeek, segment.dayOfMonth)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.INCREMENT, segment.dayOfWeek)">

      Every
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfWeek, mode.INCREMENT)"
    (change)="setInValue(mode.INCREMENT, segment.dayOfWeek, 1, $event.target.value)">

    <option
      *ngFor="let item of daysOfWeekEvery"
      [value]="item.value"
      [selected]="getModelValues(mode.INCREMENT, segment.dayOfWeek)[1] === item.value">
      {{item.value}}
    </option>
  </select>

  <label [attr.for]="genId(mode.INCREMENT, segment.dayOfWeek)">
    day(s) starting on
  </label>

	<select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfWeek, mode.INCREMENT)"
    (change)="setInValue(mode.INCREMENT, segment.dayOfWeek, 0, $event.target.value)">

		<option
			*ngFor="let item of daysOfWeek"
			[value]="item.value"
      [selected]="getModelValues(mode.INCREMENT, segment.dayOfWeek)[0] === item.value">
			{{item.label}}
		</option>
	</select>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.INCREMENT, segment.dayOfMonth)"
      [value]="mode.INCREMENT"
      [checked]="dayOfMonth.selected === mode.INCREMENT"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.INCREMENT, segment.dayOfMonth, segment.dayOfWeek)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.INCREMENT, segment.dayOfMonth)">

      Every
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfMonth, mode.INCREMENT)"
    (change)="setInValue(mode.INCREMENT, segment.dayOfMonth, 1, $event.target.value)">

    <option
      *ngFor="let item of daysOfMonth"
      [value]="item.value"
      [selected]="getModelValues(mode.INCREMENT, segment.dayOfMonth)[1] === item.value">
      {{item.value}}
    </option>
  </select>

  <label [attr.for]="genId(mode.INCREMENT, segment.dayOfMonth)">
    day(s) starting on the
  </label>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfMonth, mode.INCREMENT)"
    (change)="setInValue(mode.INCREMENT, segment.dayOfMonth, 0, $event.target.value)">

    <option
      *ngFor="let item of daysOfMonthEvery"
      [value]="item.value"
      [selected]="getModelValues(mode.INCREMENT, segment.dayOfMonth)[0] === item.value">
      {{item.label}}
    </option>
  </select>

  <label [attr.for]="genId(mode.INCREMENT, segment.dayOfMonth)">
    of the month
  </label>
</div>

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.AND, segment.dayOfWeek)"
      [value]="mode.INCREMENT"
      [checked]="dayOfWeek.selected === mode.AND"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.AND, segment.dayOfWeek, segment.dayOfMonth)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.AND, segment.dayOfWeek)">

      Specific day of week (choose one or many)
    </label>
  </div>

  <div class="row pl-3 pt-1">
    <div
      *ngFor="let item of daysOfWeekCodes"
      class="col-2">

      <div class="form-check">
        <input
          class="form-check-input"
          type="checkbox"
          [attr.id]="genId(mode.AND, segment.dayOfWeek + item.value)"
          [value]="item.value"
          [disabled]="isDisabled(segment.dayOfWeek, mode.AND)"
          [checked]="inSpecificsList(item.value, mode.AND, segment.dayOfWeek)"
          (change)="toggleSpecifics(item.value, mode.AND, segment.dayOfWeek)">

        <label
          class="form-check-label"
          [attr.for]="genId(mode.AND, segment.dayOfWeek + item.value)">
          {{item.label}}
        </label>
      </div>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.AND, segment.dayOfMonth)"
      [value]="mode.INCREMENT"
      [checked]="dayOfMonth.selected === mode.AND"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.AND, segment.dayOfMonth, segment.dayOfWeek)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.AND, segment.dayOfMonth)">

      Specific day of month (choose one or many)
    </label>
  </div>

  <div class="row pl-3 pt-1">
    <div
      *ngFor="let item of daysOfMonth"
      class="col-1">

      <div class="form-check">
        <input
          class="form-check-input"
          type="checkbox"
          [attr.id]="genId(mode.AND, segment.dayOfMonth + item.value)"
          [value]="item.value"
          [disabled]="isDisabled(segment.dayOfMonth, mode.AND)"
          [checked]="inSpecificsList(item.value, mode.AND, segment.dayOfMonth)"
          (change)="toggleSpecifics(item.value, mode.AND, segment.dayOfMonth)">

        <label
          class="form-check-label"
          [attr.for]="genId(mode.AND, segment.dayOfMonth + item.value)">
          {{item.label}}
        </label>
      </div>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.LAST_DAY, segment.dayOfMonth)"
      [value]="mode.LAST_DAY"
      [checked]="dayOfMonth.selected === mode.LAST_DAY"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.LAST_DAY, segment.dayOfMonth, segment.dayOfWeek, 'L')">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.LAST_DAY, segment.dayOfMonth)">

      On the last day of the month
    </label>
  </div>
</div>

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.LAST_DAY_WEEK, segment.dayOfMonth)"
      [value]="mode.LAST_DAY_WEEK"
      [checked]="dayOfMonth.selected === mode.LAST_DAY_WEEK"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.LAST_DAY_WEEK, segment.dayOfMonth, segment.dayOfWeek, 'LW')">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.LAST_DAY_WEEK, segment.dayOfMonth)">

      On the last weekday of the month
    </label>
  </div>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.LAST_NTH_DAY_WEEK, segment.dayOfWeek)"
      [value]="mode.LAST_NTH_DAY_WEEK"
      [checked]="dayOfWeek.selected === mode.LAST_NTH_DAY_WEEK"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.LAST_NTH_DAY_WEEK, segment.dayOfWeek, segment.dayOfMonth)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.LAST_NTH_DAY_WEEK, segment.dayOfWeek)">

      On the last
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfWeek, mode.LAST_NTH_DAY_WEEK)"
    (change)="setInValue(mode.LAST_NTH_DAY_WEEK, segment.dayOfWeek, 0, $event.target.value)">

    <option
      *ngFor="let item of daysOfWeek"
      [value]="item.value + 'L'"
      [selected]="getModelValues(mode.LAST_NTH_DAY_WEEK, segment.dayOfWeek)[0] === item.value">
      {{item.label}}
    </option>
  </select>

  <label [attr.for]="genId(mode.LAST_NTH_DAY_WEEK, segment.dayOfWeek)">
    of the month
  </label>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.DAYS_BEFORE_END_MONTH, segment.dayOfMonth)"
      [value]="mode.DAYS_BEFORE_END_MONTH"
      [checked]="dayOfMonth.selected === mode.DAYS_BEFORE_END_MONTH"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.DAYS_BEFORE_END_MONTH, segment.dayOfMonth, segment.dayOfWeek)">
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfMonth, mode.DAYS_BEFORE_END_MONTH)"
    (change)="setInValue(mode.DAYS_BEFORE_END_MONTH, segment.dayOfMonth, 0, $event.target.value)">

    <option
      *ngFor="let item of daysOfMonth"
      [value]="'L-' + item.value"
      [selected]="getModelValues(mode.DAYS_BEFORE_END_MONTH, segment.dayOfMonth)[0] === item.value">
      {{item.label}}
    </option>
  </select>

  <label [attr.for]="genId(mode.DAYS_BEFORE_END_MONTH, segment.dayOfMonth)">
    day(s) before the end of the month
  </label>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.NEAREST_WEEKDAY_OF_MONTH, segment.dayOfMonth)"
      [value]="mode.NEAREST_WEEKDAY_OF_MONTH"
      [checked]="dayOfMonth.selected === mode.NEAREST_WEEKDAY_OF_MONTH"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.NEAREST_WEEKDAY_OF_MONTH, segment.dayOfMonth, segment.dayOfWeek)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.NEAREST_WEEKDAY_OF_MONTH, segment.dayOfMonth)">

      Nearest weekday (Monday to Friday) to the
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfMonth, mode.NEAREST_WEEKDAY_OF_MONTH)"
    (change)="setInValue(mode.NEAREST_WEEKDAY_OF_MONTH, segment.dayOfMonth, 0, $event.target.value)">

    <option
      *ngFor="let item of daysOfMonthEvery"
      [value]="item.value + 'W'"
      [selected]="getModelValues(mode.NEAREST_WEEKDAY_OF_MONTH, segment.dayOfMonth)[0] === item.value">
      {{item.label}}
    </option>
  </select>

  <label [attr.for]="genId(mode.NEAREST_WEEKDAY_OF_MONTH, segment.dayOfMonth)">
    of the month
  </label>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.NTH_WEEKDAY_OF_MONTH, segment.dayOfWeek)"
      [value]="mode.NTH_WEEKDAY_OF_MONTH"
      [checked]="dayOfWeek.selected === mode.NTH_WEEKDAY_OF_MONTH"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.NTH_WEEKDAY_OF_MONTH, segment.dayOfWeek, segment.dayOfMonth)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.NTH_WEEKDAY_OF_MONTH, segment.dayOfWeek)">

      On the
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfWeek, mode.NTH_WEEKDAY_OF_MONTH)"
    (change)="setInValue(mode.NTH_WEEKDAY_OF_MONTH, segment.dayOfWeek, 1, $event.target.value)">

    <option
      *ngFor="let item of limitedDaysOfMonth"
      [value]="item.value"
      [selected]="getModelValues(mode.NTH_WEEKDAY_OF_MONTH, segment.dayOfWeek)[1] === item.value">
      {{item.label}}
    </option>
  </select>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(segment.dayOfWeek, mode.NTH_WEEKDAY_OF_MONTH)"
    (change)="setInValue(mode.NTH_WEEKDAY_OF_MONTH, segment.dayOfWeek, 0, $event.target.value)">

    <option
      *ngFor="let item of daysOfWeek"
      [value]="item.value"
      [selected]="getModelValues(mode.NTH_WEEKDAY_OF_MONTH, segment.dayOfWeek)[0] === item.value">
      {{item.label}}
    </option>
  </select>

  <label [attr.for]="genId(mode.NTH_WEEKDAY_OF_MONTH, segment.dayOfWeek)">
    of the month
  </label>
</div>

// libs/re-cron/src/lib/unix/tabs/day/day.tsx
import React from 'react';
import { Segment, UnixService, Mode, ViewDataItem, CronJobsSelectOption } from '@sbzen/cron-core';

import { TabBaseProps, TabBaseState, TabBaseComponent } from './../tab-base.abstract';

type TabSegments = Segment.dayOfMonth|Segment.dayOfWeek;

type ReCronDayState = {
	daysOfWeekEvery: CronJobsSelectOption[];
	daysOfWeek: CronJobsSelectOption[];
	daysOfWeekCodes: CronJobsSelectOption[];
	daysOfMonthEvery: CronJobsSelectOption[];
	daysOfMonth: CronJobsSelectOption[];
	limitedDaysOfMonth: CronJobsSelectOption[];
	dayOfMonth: ViewDataItem;
	dayOfWeek: ViewDataItem;
} & TabBaseState<TabSegments>;

export class ReCronDay extends TabBaseComponent<TabBaseProps, ReCronDayState, TabSegments> {
	constructor(props: TabBaseProps) {
		super(props, [Segment.dayOfMonth, Segment.dayOfWeek]);
		const coreService = new UnixService();
		const daysOfMonthEvery = coreService.getList(Segment.dayOfMonth, true);
		this.state = {
			daysOfWeekEvery: coreService.getList(Segment.dayOfWeek, true),
			daysOfWeek: coreService.getList(Segment.dayOfWeek),
			daysOfWeekCodes: coreService.getDaysOfWeekCodes(),
			daysOfMonthEvery: daysOfMonthEvery,
			daysOfMonth: coreService.getList(Segment.dayOfMonth),
			limitedDaysOfMonth: daysOfMonthEvery.slice(0, 5),
			dayOfMonth: this.getView(Segment.dayOfMonth),
			dayOfWeek: this.getView(Segment.dayOfWeek)
		};
	}

	render() {
		return (
			<div>
				{this.genEvery()}
				{this.genDayOfWeekIncrement()}
				{this.genDayOfMonthIncrement()}
				{this.genDayOfWeekAnd()}
				{this.genDayOfMonthAnd()}
			</div>
		);
	}

	private genEvery() {
		const isChecked = [
			this.state.dayOfWeek.selected === Mode.EVERY,
			this.state.dayOfMonth.selected !== Mode.INCREMENT,
			this.state.dayOfMonth.selected !== Mode.AND
		].every(r => !!r);

		return (
			<div className={this.genClassName(['form-group'], ['c-every-weekday'])}>
				<div className={this.genClassName(['form-check'], ['c-every-weekday-check'])}>
					<input
						className={this.genClassName(['form-check-input'], ['c-every-weekday-option'])}
						type="radio"
						id={this.genId(Mode.EVERY, Segment.dayOfWeek)}
						value={Mode.EVERY}
						checked={isChecked}
						disabled={this.isDisabled()}
						onChange={() => this.setEvery()} />

					<label
						className={this.genClassName(['form-check-label'], ['c-every-weekday-option-label'])}
						htmlFor={this.genId(Mode.EVERY, Segment.dayOfWeek)}>

						{this.props.localization.unix.day.every.label}
					</label>
				</div>
			</div>
		);
	}

	private genDayOfWeekIncrement() {
		return (
			<div className={this.genClassName(['form-group', 'form-inline'], ['c-increment-weekday'])}>
				<div className={this.genClassName(['form-check'], ['c-increment-weekday-check'])}>
					<input
						className={this.genClassName(['form-check-input'], ['c-increment-weekday-option'])}
						type="radio"
						id={this.genId(Mode.INCREMENT, Segment.dayOfWeek)}
						value={Mode.INCREMENT}
						checked={this.state.dayOfWeek.selected === Mode.INCREMENT}
						disabled={this.isDisabled()}
						onChange={() => this.setSelected(Mode.INCREMENT, Segment.dayOfWeek, Segment.dayOfMonth)} />

					<label
						className={this.genClassName(['form-check-label'], ['c-increment-weekday-option-label'])}
						htmlFor={this.genId(Mode.INCREMENT, Segment.dayOfWeek)}>

						{this.props.localization.unix.day.dayOfWeekIncrement.label1}
					</label>
				</div>

				<select
					className={this.genClassName(['form-control', 'form-control-sm', 'mx-1'], ['c-increment-weekday-every'])}
					disabled={this.isDisabled(Mode.INCREMENT, Segment.dayOfWeek)}
					value={this.getValues(Mode.INCREMENT, Segment.dayOfWeek)[1]}
					onChange={(e) => this.setInValue(Mode.INCREMENT, 1, e.target.value, Segment.dayOfWeek)}>

					{this.state.daysOfWeekEvery.map(item => {
						return (
							<option
								value={item.value}
								key={item.value}>
								{item.value}
							</option>
						);
					})}
				</select>

				<label
					className="c-increment-weekday-option-label2"
					htmlFor={this.genId(Mode.INCREMENT, Segment.dayOfWeek)}>
					{this.props.localization.unix.day.dayOfWeekIncrement.label2}
				</label>
			</div>
		);
	}

	private genDayOfMonthIncrement() {
		return (
			<div className={this.genClassName(['form-group', 'form-inline'], ['c-increment-monthday'])}>
				<div className={this.genClassName(['form-check'], ['c-increment-monthday-check'])}>
					<input
						className={this.genClassName(['form-check-input'], ['c-increment-monthday-option'])}
						type="radio"
						id={this.genId(Mode.INCREMENT, Segment.dayOfMonth)}
						value={Mode.INCREMENT}
						checked={this.state.dayOfMonth.selected === Mode.INCREMENT}
						disabled={this.isDisabled()}
						onChange={() => this.setSelected(Mode.INCREMENT, Segment.dayOfMonth, Segment.dayOfWeek)} />

					<label
						className={this.genClassName(['form-check-label'], ['c-increment-monthday-option-label'])}
						htmlFor={this.genId(Mode.INCREMENT, Segment.dayOfMonth)}>
						{this.props.localization.unix.day.dayOfMonthIncrement.label1}
					</label>
				</div>

				<select
					className={this.genClassName(['form-control', 'form-control-sm', 'mx-1'], ['c-increment-monthday-every'])}
					disabled={this.isDisabled(Mode.INCREMENT, Segment.dayOfMonth)}
					value={this.getValues(Mode.INCREMENT, Segment.dayOfMonth)[1]}
					onChange={(e) => this.setInValue(Mode.INCREMENT, 1, e.target.value, Segment.dayOfMonth)}>

					{this.state.daysOfMonth.map(item => {
						return (
							<option
								key={item.value}
								value={item.value}>
								{item.value}
							</option>
						);
					})}
				</select>

				<label
					className="c-increment-monthday-option-label2"
					htmlFor={this.genId(Mode.INCREMENT, Segment.dayOfMonth)}>
					{this.props.localization.unix.day.dayOfMonthIncrement.label2}
				</label>
			</div>
		);
	}

	private genDayOfWeekAnd() {
		return (
			<div className={this.genClassName(['form-group'], ['c-and-weekday'])}>
				<div className={this.genClassName(['form-check'], ['c-and-weekday-check'])}>
					<input
						className={this.genClassName(['form-check-input'], ['c-and-weekday-option'])}
						type="radio"
						id={this.genId(Mode.AND, Segment.dayOfWeek)}
						value={Mode.INCREMENT}
						checked={this.state.dayOfWeek.selected === Mode.AND}
						disabled={this.isDisabled()}
						onChange={() => this.setSelected(Mode.AND, Segment.dayOfWeek, Segment.dayOfMonth)} />

					<label
						className={this.genClassName(['form-check-label'], ['c-and-weekday-option-label'])}
						htmlFor={this.genId(Mode.AND, Segment.dayOfWeek)}>
						{this.props.localization.unix.day.dayOfWeekAnd.label}
					</label>
				</div>

				<div className={this.genClassName(['row', 'pl-3', 'pt-1'], ['c-and-weekday-list'])}>
					{this.state.daysOfWeekCodes.map(item => {
						return (
							<div
								className={this.genClassName(['col-2'], ['c-and-weekday-item'])}
								item-value={item.value}
								key={item.value}>

								<div className={this.genClassName(['form-check'], ['c-and-weekday-item-check'])}>
									<input
										className={this.genClassName(['form-check-input'], ['c-and-weekday-item-field'])}
										type="checkbox"
										id={this.genId(Mode.AND, Segment.dayOfWeek + item.value)}
										value={item.value}
										disabled={this.isDisabled(Mode.AND, Segment.dayOfWeek)}
										checked={this.inSpecificsList(item.value, Mode.AND, Segment.dayOfWeek)}
										onChange={() => this.toggleSpecifics(item.value, Mode.AND, Segment.dayOfWeek)} />

									<label
										className={this.genClassName(['form-check-label'], ['c-and-weekday-item-label'])}
										htmlFor={this.genId(Mode.AND, Segment.dayOfWeek + item.value)}>
										{this.props.localization.common.dayOfWeek[item.label.toLowerCase()]}
									</label>
								</div>
							</div>
						);
					})}
				</div>
			</div>
		);
	}

	private genDayOfMonthAnd() {
		return (
			<div className={this.genClassName(['form-group'], ['c-and-monthday'])}>
				<div className={this.genClassName(['form-check'], ['c-and-monthday-check'])}>
					<input
						className={this.genClassName(['form-check-input'], ['c-and-monthday-option'])}
						type="radio"
						id={this.genId(Mode.AND, Segment.dayOfMonth)}
						value={Mode.INCREMENT}
						checked={this.state.dayOfMonth.selected === Mode.AND}
						disabled={this.isDisabled()}
						onChange={() => this.setSelected(Mode.AND, Segment.dayOfMonth, Segment.dayOfWeek)} />

					<label
						className={this.genClassName(['form-check-label'], ['c-and-monthday-option-label'])}
						htmlFor={this.genId(Mode.AND, Segment.dayOfMonth)}>
						{this.props.localization.unix.day.dayOfMonthAnd.label}
					</label>
				</div>

				<div className={this.genClassName(['row', 'pl-3', 'pt-1'], ['c-and-monthday-list'])}>
					{this.state.daysOfMonth.map(item => {
						return (
							<div
								className={this.genClassName(['col-1'], ['c-and-monthday-item'])}
								item-value={item.value}
								key={item.value}>
	
								<div className={this.genClassName(['form-check'], ['c-and-monthday-item-check'])}>
									<input
										className={this.genClassName(['form-check-input'], ['c-and-monthday-item-field'])}
										type="checkbox"
										id={this.genId(Mode.AND, Segment.dayOfMonth + item.value)}
										value={item.value}
										disabled={this.isDisabled(Mode.AND, Segment.dayOfMonth)}
										checked={this.inSpecificsList(item.value, Mode.AND, Segment.dayOfMonth)}
										onChange={() => this.toggleSpecifics(item.value, Mode.AND, Segment.dayOfMonth)} />
	
									<label
										className={this.genClassName(['form-check-label'], ['c-and-monthday-item-label'])}
										htmlFor={this.genId(Mode.AND, Segment.dayOfMonth + item.value)}>
										{item.label}
									</label>
								</div>
							</div>
						);
					})}
				</div>
			</div>
		);
	}

	private setEvery() {
		const dayOfMonth = this.getView(Segment.dayOfMonth);
		dayOfMonth.values.NONE.values = ['*'];
		dayOfMonth.selected = Mode.NONE;
		this.setView(Segment.dayOfMonth, dayOfMonth);
		const dayOfWeek = this.getView(Segment.dayOfWeek);
		dayOfWeek.values.EVERY.values = ['*'];
		dayOfWeek.selected = Mode.EVERY;
		this.setView(Segment.dayOfWeek, dayOfWeek);
		this.applyChanges();
	}

	private setSelected(mode: Mode, segment: TabSegments, reset?: TabSegments, value?: string) {
		const view = this.getView(segment);
		view.selected = mode;
		this.setView(segment, view);

		if (reset === Segment.dayOfMonth) {
			this.resetsDaysOfMonth();
		}
		if (reset === Segment.dayOfWeek) {
			this.resetDaysOfWeek();
		}
		if (value) {
			this.setInValue(mode, 0, value, segment);
		}
		this.applyChanges();
	}

	private resetsDaysOfMonth() {
		const dayOfMonth = this.getView(Segment.dayOfMonth);
		dayOfMonth.selected = Mode.NONE;
		dayOfMonth.values.NONE.values = ['*'];
		this.setView(Segment.dayOfMonth, dayOfMonth);
	}

	private resetDaysOfWeek() {
		const dayOfWeek = this.getView(Segment.dayOfWeek);
		dayOfWeek.selected = Mode.NONE;
		dayOfWeek.values.NONE.values = ['*'];
		this.setView(Segment.dayOfWeek, dayOfWeek);
	}
}
