// libs/cron-bootstrap/src/lib/cron.component.ts
import { Component, forwardRef, Input, ChangeDetectionStrategy } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

import { Type, Segment, CoreService } from '@sbzen/core';

import { tabs } from './tabs/tabs';
import { CronBootstrapService } from './cron.service';

@Component({
  selector: 'cron-bootstrap',
  templateUrl: './cron.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [
    CronBootstrapService,
    CoreService,
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CronBootstrapComponent),
      multi: true
    }
  ]
})
export class CronBootstrapComponent implements ControlValueAccessor {
  @Input()
  get disabled(): boolean {
    return this.isDisabled;
  }
  set disabled(value) {
    this.isDisabled = value != null && `${value}` !== 'false';
  }

  private onChange: (cronValue: string) => {};
  private isDisabled = false;

  type = Type;
  segment = Segment;
  tabs = tabs;
  tab = this.tabs[0];

  constructor(private cronBootstrap: CronBootstrapService) {}

  getView(segment: Segment) {
    return this.cronBootstrap.getView(segment);
  }

  writeValue(cronValue: string) {
    this.cronBootstrap.fillFromExpression(cronValue);

    if (this.onChange) {
      this.applyChanges();
    }
  }

  registerOnChange(fn: (cronValue: string) => {}) {
    this.onChange = fn;
  }

  registerOnTouched() {}

  applyChanges() {
    const str = this.cronBootstrap.toString();
    this.onChange(str);
  }
}

<ul class="nav nav-tabs mb-2">
	<button
		*ngFor="let item of tabs"
		type="button"
		class="nav-link"
		[class.active]="tab === item"
		(click)="tab = item">

		{{item.label}}
	</button>
</ul>

<ng-container [ngSwitch]="tab.type">
  <cron-month
    *ngSwitchCase="type.MONTH"
    [view]="getView(segment.month)"
    [disabled]="disabled"
    (changed)="applyChanges()">
  </cron-month>

  <cron-minute
    *ngSwitchCase="type.MINUTES"
    [view]="getView(segment.minutes)"
    [disabled]="disabled"
    (changed)="applyChanges()">
  </cron-minute>

  <cron-hour
    *ngSwitchCase="type.HOURS"
    [view]="getView(segment.hours)"
    [disabled]="disabled"
    (changed)="applyChanges()">
  </cron-hour>

  <cron-second
    *ngSwitchCase="type.SECONDS"
    [view]="getView(segment.seconds)"
    [disabled]="disabled"
    (changed)="applyChanges()">
  </cron-second>

  <cron-year
    *ngSwitchCase="type.YEAR"
    [view]="getView(segment.year)"
    [disabled]="disabled"
    (changed)="applyChanges()">
  </cron-year>

  <cron-day
    *ngSwitchCase="type.DAY"
    [dayOfMonth]="getView(segment.dayOfMonth)"
    [dayOfWeek]="getView(segment.dayOfWeek)"
    [disabled]="disabled"
    (changed)="applyChanges()">
  </cron-day>
</ng-container>

// libs/re-cron/src/lib/cron.tsx
import React from 'react';

import './cron.scss';

import { Type } from '@sbzen/cron-core';

import { ReCronSecond } from './tabs/second/second';
import { ReCronMinute } from './tabs/minute/minute';
import { ReCronHour } from './tabs/hour/hour';
import { ReCronMonth } from './tabs/month/month';
import { ReCronYear } from './tabs/year/year';
import { ReCronDay } from './tabs/day/day';
import { tabs, Tab } from './tabs/tabs';
import { QuartzCronDI } from './cron-di';

type ReCronProps = {
	cssClassPrefix?: string;
	disabled?: boolean,
	value?: string,
	onChange?: (cronValue: string) => void
}

type ReCronState = {
	tab: Tab,
	session: number
};

export class ReCron extends React.Component<ReCronProps, ReCronState> {
	constructor(props: ReCronProps) {
		super(props);

		this.state = {
			tab: tabs[0],
			session: Date.now()
		};
	}

	render() {
		QuartzCronDI.get(this.state.session).fillFromExpression(this.props.value);

		console.log('RENDER');
		return (
			<div className="c-host">
				{this.genTabs()}

				<div
					className="c-tab-content"
					role="tabpanel"
					tabIndex={0}
					tab-name={this.state.tab.type}>
					{this.genContent()}
				</div>
			</div>
		);
	}

	private genContent() {
		const second = (
			<ReCronSecond
				session={this.state.session}
				cssClassPrefix={this.getCssClassPrefix()}
				disabled={this.props.disabled}
				onChange={() => this.applyChanges()}>
			</ReCronSecond>
		);
		const minute = (
			<ReCronMinute
				session={this.state.session}
				cssClassPrefix={this.getCssClassPrefix()}
				disabled={this.props.disabled}
				onChange={() => this.applyChanges()}>
			</ReCronMinute>
		);
		const hour = (
			<ReCronHour
				session={this.state.session}
				cssClassPrefix={this.getCssClassPrefix()}
				disabled={this.props.disabled}
				onChange={() => this.applyChanges()}>
			</ReCronHour>
		);
		const month = (
			<ReCronMonth
				session={this.state.session}
				cssClassPrefix={this.getCssClassPrefix()}
				disabled={this.props.disabled}
				onChange={() => this.applyChanges()}>
			</ReCronMonth>
		);
		const year = (
			<ReCronYear
				session={this.state.session}
				cssClassPrefix={this.getCssClassPrefix()}
				disabled={this.props.disabled}
				onChange={() => this.applyChanges()}>
			</ReCronYear>
		);
		const day = (
			<ReCronDay
				session={this.state.session}
				cssClassPrefix={this.getCssClassPrefix()}
				disabled={this.props.disabled}
				onChange={() => this.applyChanges()}>
			</ReCronDay>
		);
		const map = new Map<Type, JSX.Element>([
			[Type.SECONDS, second],
			[Type.MINUTES, minute],
			[Type.HOURS, hour],
			[Type.MONTH, month],
			[Type.YEAR, year],
			[Type.DAY, day]
		]);
		return map.get(this.state.tab.type);
	}

	private genTabs() {
		const className = this.genClassName(['nav', 'nav-tabs', 'mb-2'], ['c-tabs']);
		return (
			<ul
				className={className}
				role="tablist"
				aria-label="Cron Generator Tabs">

				{tabs.map(t => this.genTab(t))}
			</ul>
		);
	}

	private genTab(item: Tab) {
		const isActive = this.state.tab === item;
		const className = this.genClassName(['nav-link'], [this.state.tab.type, 'c-tab', isActive ? 'active': '']);
		return (
			<button
				key={item.type}
				role="tab"
				type="button"
				className={className}
				aria-selected={isActive}
				tabIndex={isActive ? 0 : -1}
				onClick={() => this.changeTab(item)}>

				{item.label}
			</button>
		);
	}

	private applyChanges() {
		const str = QuartzCronDI.get(this.state.session).toString();
		if (this.props.onChange) {
			this.props.onChange(str);
		}
	}

	private changeTab(item: Tab) {
		this.setState({
			tab: item
		});
	}

	private getCssClassPrefix() {
		return this.props.cssClassPrefix || '';
	}

	private genClassName(classes: string[], noPrefixClasses: string[] = []) {
		const prefixed = classes.map(c => this.getCssClassPrefix() + c);
		return prefixed.concat(noPrefixClasses).join(' ');
	}
}
