// apps/test-re-cron/src/app/container.tsx
import React, { useState } from 'react';
import { Tab } from '@sbzen/re-cron';

import { getLocalizationPathes, getLocalization } from './localization';

export const TestContainer = ({
	type = '',
	render,
	initialValue,
	initialTabs = [Tab.SECONDS, Tab.MINUTES, Tab.HOURS, Tab.DAY, Tab.MONTH, Tab.YEAR]
}) => {
	const [value, setValue] = useState(initialValue);
	const [disabled, setDisabled] = useState(false);
	const [hideTabs, setHideTabs] = useState(false);
	const [cssClassPrefix, setCssClassPrefix] = useState(undefined);
	const [activeTab, setActiveTab] = useState(undefined);
	const [localization, setLocalization] = useState(undefined);
	const [tabs, setTabs] = useState(undefined);

	const getLocalizationValue = (path: string, loc = getLocalization()) => {
		const paths = path.split('.');
		const lastProp = paths[paths.length - 1];
		const store = paths.slice(0, paths.length - 1).reduce((acc, prop) => acc[prop], loc);
		return store[lastProp];
	}

	const updateLocalizationField = (path: string, localizationValue: string) => {
		const paths = path.split('.');
		const lastProp = paths[paths.length - 1];
		const store = paths.slice(0, paths.length - 1).reduce((acc, prop) => acc[prop], localization);
		store[lastProp] = localizationValue;
		setLocalization({ ...localization });
	};

	const addedTab = (tab: Tab) => (tabs || []).includes(tab);

	const toggleTab = (tab: Tab) => {
		const tabsToUse = tabs || [];
		if (addedTab(tab)) {
			setTabs(tabsToUse.filter(t => t !== tab));
			return;
		}
		setTabs([
			...tabsToUse,
			tab
		]);
	};

	return (
		<div
			className="re-cron-test"
			data-cron-type={type}>

			<h1>{type}</h1>

			<input
				data-cron="value"
				value={value}
				onChange={e => setValue(e.target.value)}/>

			<button 
				data-cron-action="localization-reset"
				className="ml-1"
				onClick={() => setLocalization(undefined)}>
				Reset Localization
			</button>
			<button
				data-cron-action="localization-use"
				className="ml-1"
				onClick={() => setLocalization(localization || getLocalization())}>
				Use Localization
			</button>
			<button
				data-cron-action="disable"
				className="ml-1"
				onClick={() => setDisabled(!disabled)}>
				Disable
			</button>
			<button 
				data-cron-action="hide-tabs"
				className="ml-1"
				onClick={() => setHideTabs(true)}>
				Hide tabs
			</button>
			<button 
				data-cron-action="show-tabs"
				className="ml-1"
				onClick={() => setHideTabs(false)}>
				Show tabs
			</button>
			<button 
				data-cron-action="add-css-class-prefix"
				className="ml-1"
				onClick={() => setCssClassPrefix('my-')}>
				Add "my-" css prefix
			</button>
			<button 
				data-cron-action="remove-css-class-prefix"
				className="ml-1"
				onClick={() => setCssClassPrefix(undefined)}>
				Remove "my-" css prefix
			</button>

			<div className="mt-1">
				{getLocalizationPathes().map((path, i) => (
					<input
						data-cron-action="localization-field"
						data-cron-action-value={path}
						className="mr-1 mw-fixed-70"
						key={i}
						disabled={!localization}
						placeholder={path}
						value={getLocalizationValue(path, localization)}
						onChange={e => updateLocalizationField(path, e.target.value)}/>
				))}
			</div>

			<div className="mt-1">
				<button
					className="mr-1"
					data-cron-action="reset-tab"
					onClick={() => setTabs(undefined)}>
					Reset Tabs
				</button>
				<button
					className="mr-1"
					data-cron-action="hide-tab"
					onClick={() => setTabs([])}>
					Remove Tabs
				</button>
				{initialTabs.map((tab, i) => (
					<button
						className="mr-1"
						data-cron-action="toggle-tab"
						data-cron-action-value={tab}
						key={i}
						onClick={() => toggleTab(tab)}>
						{tab}
						{addedTab(tab) ? '-' : '+'}
					</button>
				))}
			</div>

			<div className="mt-1">
				{initialTabs.map((tab, i) => (
					<button
						className="mr-1"
						data-cron-action="change-tab"
						data-cron-action-value={tab}
						key={i}
						onClick={() => setActiveTab(tab)}>
						{tab}
					</button>
				))}
			</div>

			<div data-cron-active-tab={activeTab}>
				{activeTab}
			</div>

			<div data-cron-host>
				{render({
					value,
					cssClassPrefix,
					localization,
					activeTab,
					tabs,
					onChange: setValue,
					hideTabs,
					onTabChange: setActiveTab,
					disabled
				})}
			</div>
		</div>
	);
};

// apps/test-ng-cron/src/app/container/container.component.ts
import { Component, EventEmitter, Output, Input, ContentChild, TemplateRef, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';

import { Tab, CronLocalization } from '@sbzen/ng-cron';

import { getLocalizationPathes, getLocalization } from './localization';

@Component({
	selector: 'container',
	templateUrl: './container.html',
	changeDetection: ChangeDetectionStrategy.OnPush
})
export class ContainerComponent {
	@ContentChild('content') content: TemplateRef<HTMLDivElement>;
	@Output() ticked = new EventEmitter<void>();
	@Input() type = '';
	@Input() value = '';
	@Input() initialTabs = [Tab.SECONDS, Tab.MINUTES, Tab.HOURS, Tab.DAY, Tab.MONTH, Tab.YEAR];

	disabled = false;
	hideTabs = false;
	cssClassPrefix = '';
	activeTab: Tab|undefined = undefined;
	tabs: Tab[]|undefined = undefined;
	localization: CronLocalization|undefined = undefined;

	constructor(private readonly cd: ChangeDetectorRef) {}

	updateValue = (v: string) => this.setValue(v);
	updateActiveTab = (v: Tab) => this.setActiveTab(v);

	setValue(v: string) {
		this.value = v;
		
		this.cd.detectChanges();
		this.ticked.emit();
	}

	setDisabled(v?: boolean) {
		this.disabled = v;
		
		this.ticked.emit();
		this.cd.detectChanges();
	}

	setHideTabs(v?: boolean) {
		this.hideTabs = v;
		
		this.cd.detectChanges();
	}

	setCssClassPrefix(v?: string) {
		this.cssClassPrefix = v;
		
		this.cd.detectChanges();
	}

	setActiveTab(v?: Tab) {
		this.activeTab = v;
		
		this.cd.detectChanges();
	}

	setLocalization(v?: CronLocalization) {
		this.localization = v;
		
		this.cd.detectChanges();
	}

	setTabs(v?: Tab[]) {
		this.tabs = v;
		
		this.cd.detectChanges();
	}
	
	getLocalization() {
		return getLocalization();
	}

	getLocalizationPathes() {
		return getLocalizationPathes();
	}

	getLocalizationValue(path: string, loc = getLocalization()) {
		const paths = path.split('.');
		const lastProp = paths[paths.length - 1];
		const store = paths.slice(0, paths.length - 1).reduce((acc, prop) => acc[prop], loc);
		return store[lastProp];
	}

	updateLocalizationField(path: string, localizationValue: string) {
		const paths = path.split('.');
		const lastProp = paths[paths.length - 1];
		const store = paths.slice(0, paths.length - 1).reduce((acc, prop) => acc[prop], this.localization);
		store[lastProp] = localizationValue;
		this.setLocalization({ ...this.localization });
	}

	addedTab(tab: Tab) {
		return (this.tabs || []).includes(tab);
	}

	toggleTab(tab: Tab) {
		const tabsToUse = this.tabs || [];
		if (this.addedTab(tab)) {
			this.setTabs(tabsToUse.filter(t => t !== tab));
			return;
		}
		this.setTabs([
			...tabsToUse,
			tab
		]);
	}
}
