// libs/cron-bootstrap/src/lib/tabs/month/month.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';

import { Segment, CoreService } from '@sbzen/core';

import { CronBootstrapService } from './../../cron.service';
import { TabSingleSegmentComponent } from './../tab-single-segment.component';

@Component({
  selector: 'cron-month',
  templateUrl: './month.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MonthComponent extends TabSingleSegmentComponent {
  monthCodes = this.coreService.getMonthCodes();
  monthes = this.coreService.getList(Segment.month);

  constructor(
    private coreService: CoreService,
    cronBootstrap: CronBootstrapService
  ) {
    super(Segment.month, cronBootstrap);
  }
}

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.EVERY)"
      [value]="mode.EVERY"
      [checked]="view.selected === mode.EVERY"
      [disabled]="isDisabled()"
      (change)="setEvery()">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.EVERY)">
      Every month
    </label>
  </div>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.INCREMENT)"
      [value]="mode.INCREMENT"
      [checked]="view.selected === mode.INCREMENT"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.INCREMENT)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.INCREMENT)">
      Every
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(mode.INCREMENT)"
    (change)="setInValue(mode.INCREMENT, 1, $event.target.value)">

    <option
      *ngFor="let item of monthes; index as i"
      [value]="item.value"
      [selected]="getModelValues(mode.INCREMENT)[1] === item.value">
      {{i + 1}}
    </option>
  </select>

  <label [attr.for]="genId(mode.INCREMENT)">
    month(s) starting at month
  </label>

  <select
    class="form-control form-control-sm ml-1"
    [disabled]="isDisabled(mode.INCREMENT)"
    (change)="setInValue(mode.INCREMENT, 0, $event.target.value)">

    <option
      *ngFor="let item of monthes"
      [value]="item.value"
      [selected]="getModelValues(mode.INCREMENT)[0] === item.value">
      {{item.label}}
    </option>
  </select>
</div>

<div class="form-group">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.AND)"
      [value]="mode.AND"
      [checked]="view.selected === mode.AND"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.AND)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.AND)">
      Specific month (choose one or many)
    </label>
  </div>

  <div class="row pl-3 pt-1">
    <div
      *ngFor="let item of monthCodes"
      class="col-2">

      <div class="form-check">
        <input
          class="form-check-input"
          type="checkbox"
          [attr.id]="genId(mode.AND, item.value)"
          [value]="item.value"
          [disabled]="isDisabled(mode.AND)"
          [checked]="inSpecificsList(item.value, mode.AND)"
          (change)="toggleSpecifics(item.value, mode.AND)">

        <label
          class="form-check-label"
          [attr.for]="genId(mode.AND, item.value)">
          {{item.label}}
        </label>
      </div>
    </div>
  </div>
</div>

<div class="form-group form-inline">
  <div class="form-check">
    <input
      class="form-check-input"
      type="radio"
      [attr.id]="genId(mode.RANGE)"
      [value]="mode.RANGE"
      [checked]="view.selected === mode.RANGE"
      [disabled]="isDisabled()"
      (change)="setSelected(mode.RANGE)">

    <label
      class="form-check-label"
      [attr.for]="genId(mode.RANGE)">
      Every month between month
    </label>
  </div>

  <select
    class="form-control form-control-sm mx-1"
    [disabled]="isDisabled(mode.RANGE)"
    (change)="setInValue(mode.RANGE, 0, $event.target.value)">

    <option
      *ngFor="let item of monthes"
      [value]="item.value"
      [selected]="getModelValues(mode.RANGE)[0] === item.value">
      {{item.label}}
    </option>
  </select>

  <label [attr.for]="genId(mode.RANGE)">and month</label>

  <select
    class="form-control form-control-sm ml-1"
    [disabled]="isDisabled(mode.RANGE)"
    (change)="setInValue(mode.RANGE, 1, $event.target.value)">

    <option
      *ngFor="let item of monthes"
      [value]="item.value"
      [selected]="getModelValues(mode.RANGE)[1] === item.value">
      {{item.label}}
    </option>
  </select>
</div>

// libs/re-cron/src/lib/quartz/tabs/month/month.tsx
import React from 'react';
import { Segment, QuartzService, Mode, CronJobsSelectOption } from '@sbzen/cron-core';

import { TabSingleSegmentComponent } from './../tab-single-segment.abstract';
import { TabBaseProps, TabBaseState } from './../tab-base.abstract';

type ReCronMonthState = {
	monthCodes: CronJobsSelectOption[];
	monthes: CronJobsSelectOption[];
} & TabBaseState<Segment.month>;

export class ReCronMonth extends TabSingleSegmentComponent<ReCronMonthState, Segment.month> {
	constructor(props: TabBaseProps) {
		super(props, Segment.month);

		const coreService = new QuartzService();
		this.state = {
			monthCodes: coreService.getMonthCodes(),
			monthes: coreService.getList(Segment.month),
			month: this.getView(Segment.month)
		};
	}

	protected genEvery() {
		return (
			<div className={this.genClassName(['form-group'], ['c-every'])}>
				<div className={this.genClassName(['form-check'], ['c-every-check'])}>
					<input
						className={this.genClassName(['form-check-input'], ['c-every-option'])}
						type="radio"
						id={this.genId(Mode.EVERY)}
						value={Mode.EVERY}
						checked={this.state.month.selected === Mode.EVERY}
						disabled={this.isDisabled()}
						onChange={() => {this.setEvery()}} />

					<label
						className={this.genClassName(['form-check-label'], ['c-every-option-label'])}
						htmlFor={this.genId(Mode.EVERY)}>
						{this.props.localization.quartz.month.every.label}
					</label>
				</div>
			</div>
		);
	}

	protected genIncrement() {
		return (
			<div className={this.genClassName(['form-group', 'form-inline'], ['c-increment'])}>
				<div className={this.genClassName(['form-check'], ['c-increment-check'])}>
				
					<input
						className={this.genClassName(['form-check-input'], ['c-increment-option'])}
						type="radio"
						id={this.genId(Mode.INCREMENT)}
						value={Mode.INCREMENT}
						checked={this.state.month.selected === Mode.INCREMENT}
						disabled={this.isDisabled()}
						onChange={() => this.setSelected(Mode.INCREMENT)} />

					<label
						className={this.genClassName(['form-check-label'], ['c-increment-option-label'])}
						htmlFor={this.genId(Mode.INCREMENT)}>
						{this.props.localization.quartz.month.increment.label1}
					</label>
				</div>

				<select
					className={this.genClassName(['form-control', 'form-control-sm', 'mx-1'], ['c-increment-every'])}
					disabled={this.isDisabled(Mode.INCREMENT)}
					value={this.getValues(Mode.INCREMENT)[1]}
					onChange={(e) => this.setInValue(Mode.INCREMENT, 1, e.target.value)}>

					{this.state.monthes.map((item, i) => {
						return (
							<option
								key={item.value}
								value={item.value}>
								{i + 1}
							</option>
						);
					})}
				</select>

				<label
					className="c-increment-option-label2"
					htmlFor={this.genId(Mode.INCREMENT)}>
					{this.props.localization.quartz.month.increment.label2}
				</label>

				<select
					className={this.genClassName(['form-control', 'form-control-sm', 'ml-1'], ['c-increment-from'])}
					disabled={this.isDisabled(Mode.INCREMENT)}
					value={this.getValues(Mode.INCREMENT)[0]}
					onChange={(e) => this.setInValue(Mode.INCREMENT, 0, e.target.value)}>

					{this.state.monthes.map(item => {
						return (
							<option
								key={item.value}
								value={item.value}>
								{this.props.localization.common.month[item.label.toLowerCase()]}
							</option>
						);
					})}
				</select>
			</div>
		);
	}

	protected genAnd() {
		return (
			<div className={this.genClassName(['form-group'], ['c-and'])}>
				<div className={this.genClassName(['form-check'], ['c-and-check'])}>
					<input
						className={this.genClassName(['form-check-input'], ['c-and-option'])}
						type="radio"
						id={this.genId(Mode.AND)}
						value={Mode.AND}
						checked={this.state.month.selected === Mode.AND}
						disabled={this.isDisabled()}
						onChange={() => this.setSelected(Mode.AND)} />

					<label
						className={this.genClassName(['form-check-label'], ['c-and-option-label'])}
						htmlFor={this.genId(Mode.AND)}>
						{this.props.localization.quartz.month.and.label}
					</label>
				</div>

				<div className={this.genClassName(['row', 'pl-3', 'pt-1'], ['c-and-list'])}>
					{this.state.monthCodes.map(item => {
						return (
							<div
								className={this.genClassName(['col-2'], ['c-and-item'])}
								item-value={item.value}
								key={this.genId(Mode.AND, item.value)}>

								<div className={this.genClassName(['form-check'], ['c-and-item-check'])}>
									<input
										className={this.genClassName(['form-check-input'], ['c-and-item-field'])}
										type="checkbox"
										id={this.genId(Mode.AND, item.value)}
										value={item.value}
										disabled={this.isDisabled(Mode.AND)}
										checked={this.inSpecificsList(item.value, Mode.AND)}
										onChange={() => this.toggleSpecifics(item.value, Mode.AND)} />

									<label
										className={this.genClassName(['form-check-label'], ['c-and-item-label'])}
										htmlFor={this.genId(Mode.AND, item.value)}>
										{this.props.localization.common.month[item.label.toLowerCase()]}
									</label>
								</div>
							</div>
						);
					})}
				</div>
			</div>
		);
	}

	protected genRange() {
		return (
			<div className={this.genClassName(['form-group', 'form-inline'], ['c-range'])}>
				<div className={this.genClassName(['form-check'], ['c-range-check'])}>
				
					<input
						className={this.genClassName(['form-check-input'], ['c-range-option'])}
						type="radio"
						id={this.genId(Mode.RANGE)}
						value={Mode.RANGE}
						checked={this.state.month.selected === Mode.RANGE}
						disabled={this.isDisabled()}
						onChange={() => this.setSelected(Mode.RANGE)}/>

					<label
						className={this.genClassName(['form-check-label'], ['c-range-option-label'])}
						htmlFor={this.genId(Mode.RANGE)}>
						
						{this.props.localization.quartz.month.range.label1}
					</label>
				</div>

				<select
					className={this.genClassName(['form-control', 'form-control-sm', 'mx-1'], ['c-range-from'])}
					disabled={this.isDisabled(Mode.RANGE)}
					value={this.getValues(Mode.RANGE)[0]}
					onChange={(e) => this.setInValue(Mode.RANGE, 0, e.target.value)}>

					{this.state.monthes.map(item => {
						return (
							<option
								key={item.value}
								value={item.value}>
								{this.props.localization.common.month[item.label.toLowerCase()]}
							</option>
						);
					})}
				</select>

				<label
					className="c-range-option-label2"
					htmlFor={this.genId(Mode.RANGE)}>
					
					{this.props.localization.quartz.month.range.label2}
				</label>

				<select
					className={this.genClassName(['form-control', 'form-control-sm', 'ml-1'], ['c-range-to'])}
					disabled={this.isDisabled(Mode.RANGE)}
					value={this.getValues(Mode.RANGE)[1]}
					onChange={(e) => this.setInValue(Mode.RANGE, 1, e.target.value)}>

					{this.state.monthes.map(item => {
						return (
							<option
								key={item.value}
								value={item.value}>
								{this.props.localization.common.month[item.label.toLowerCase()]}
							</option>
						);
					})}
				</select>
			</div>
		);
	}
}
